name: verify

on:
  push:

permissions:
  contents: write

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Check verify directory
      run: |
        bad=$(find verify -type f ! -name "*.test.cpp")
        if [ -n "$bad" ]; then
          echo "Unexpected files found:"
          echo "$bad"
          exit 1
        fi
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip3 install -U online-judge-verify-helper
        pip3 install "setuptools<81"

    - name: Verify
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
      run: |
        oj-verify all