name: verify

on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check verify directory
        run: |
          bad=$(find verify -type f ! -name "*.test.cpp")
          if [ -n "$bad" ]; then
            echo "Unexpected files found:"
            echo "$bad"
            exit 1
          fi
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install online-judge-tools
          pip install online-judge-verify-helper

      - name: Verify
        env:
          CXXFLAGS: -std=c++23
        run: oj-verify all